### ISSUE TITLE
Time input, milliseconds in particular.

### ISSUE THREAD

**Issue by cyclinggeorgian** [methnen/m-chart#104]
As long as time is represented in the form of real numbers charts are drawing very nicely. But, as in my case, if there is a need to denote time in the from MM:SS,00 (minutes:seconds,milliseconds) charts not recognizing this input and subsequently not drawing. 
Would it be possible to implement time recognition?

**Comment by buffaloseven** [comment]
First familiarize yourself with the ways Highcharts handles the x-axis; there may be an alternative approach you can apply in a custom theme that will solve your problem: https://api.highcharts.com/highcharts/xAxis.type

The other thing is to ensure your time follows ISO formatting; I can’t look it up right now, but I believe ISO uses a dot to separate seconds and milliseconds, but I’m not sure if that changes by region.

Hopefully that can help a bit.

**Comment by methnen** [comment]
@zarbazana Sorry for the delay. It's holidays here in the US and I haven't been on the computer for a bit.

Because Highcharts date time handling has historically been a bit goofy I've head off building it into he UI but @buffaloseven is correct. This could be handled via a theme quite easily. You'd just need to make sure the axis you are dealing with is set to datetime using the axisType parameter and then format your dates/times correctly.

Actually looking at the options settings a second time I feel like they've already done some simplifying and at the very least adding a date/time toggle for each axis would be a reasonable UI addition for a future version.

I'm going to leave this ticket open as a reminder to add this feature in the next version. Feel free to follow up as well if you need any help implementing this via a theme.
