### ISSUE TITLE
Adding custom logo to chart exports

### ISSUE THREAD

**Issue by benzien** [methnen/m-chart#124]
I've managed to get my charts almost entirely perfect-looking, including adding a custom logo as the background of the x-axis using the theme. See https://www.solarpowerrocks.com/affordable-solar/mo-test-charts/.

I also managed to add Highcharts' exporting tool to the charts so my site's users can download charts!

Therein lies the problem.  Even enabling Highcharts' (admittedly experimental) allowHTML functionality in the exporting module, the logo image doesn't carry through.

**Long question short:** how can I get my image into the exported PNG? 

I found [a jsFiddle that seems to do what I want](http://jsfiddle.net/rLfj69b9/2/), but I have no idea how to reformat the javascript to work in an M-Chart theme file. 

Would this be better done using [Highcharts.SVGRender.image](https://api.highcharts.com/class-reference/Highcharts.SVGRenderer#image)? If so, how?

Thanks in advance!

**Comment by methnen** [comment]
That jsFiddle solution won't actually work inside of a theme since it has a JS function in it.

And actually the difficulty you are running into with the Highcharts exporting features illustrates why I built my own solution that is used to generate he PNGs that get used by the plugin.

All of that said the Highcharts.SVGRender.image solution should work I think I don't believe that functionality was even there in earlier versions of HIghcharts so I'll admit to having never used it yet.

But there's an [action hook](https://github.com/methnen/m-chart/wiki/Action-and-filter-hooks#m_chart_post_render_javascript) I added that lets you insert JS code directly into the very place you'd need to replicate what they describe there.

Something like this in your WP Theme's `functions.php` file should work. It's actually the example I use in the docs for that action hook:

```php
function action_m_chart_post_render_javascript( $post_id, $args, $instance ) {
	?>
	chart.renderer.image('http://domain.com/img/logo.svg', 11, 10, 106, 16).add();
	<?php
}

add_action( 'm_chart_post_render_javascript', 'action_m_chart_post_render_javascript', 10, 3 );

```

**Comment by benzien** [comment]
Cool, I will try that. Thank you!

Any advice on wildcards if I want to enable it for all post_ids? I'm going to end up with 200+ charts and I'd like the logo to show up in the same place on all of them.

**Comment by methnen** [comment]
The way that code is written it'll already work for every chart. If you wanted to limit it you'd have to add a conditional checking against the $post_id value that get's passed to the function.

**Comment by benzien** [comment]
Well I've got the code in functions.php, and it produces a logo image in the chart. But there are a couple problems:

1.) It doesn't pass when you export as PNG
2.) It relies on x-y positioning, which changes with viewport resize and on a per-chart basis.

That said, I'm still using a PNG. Do you think if I tried an SVG it might pass with export? I've also tried base64 encoding the image as a background image of the x-axis title. That worked to display the image in the chart, but also didn't pass to export. 

Page URL again is https://www.solarpowerrocks.com/affordable-solar/mo-test-charts/

**Comment by benzien** [comment]
I got it!

In my theme, I had originally set the 'text' attribute of the x-axis title to '&nbsp;' and the background image set to a PNG on my server. Instead, I had to set it to:

`'text' => "<img src='data:image/png;base64,Base64ImgHere' width='X' height='X'>"`

And it works! It's not 100% perfect, visually, but it's darn close. I am thrilled it worked out.

**Comment by methnen** [comment]
Closing since the OP figured this out.
