### ISSUE TITLE
Notice about installing M Chart Highcharts Library plugin doesn't disappear even when it's installed

### ISSUE THREAD

**Issue by JuanDBB** [methnen/m-chart#132]
Hello,

I have installed the M Chart Highcharts Library plugin but the notice saying that it has to be installed doesn't disappear.

Thank you in advance!

**Comment by methnen** [comment]
Did you activate it?

**Comment by JuanDBB** [comment]
Hello,

Yes, activated and configurated, and works great except for a warning when saving configuration.

**Comment by methnen** [comment]
Interesting.

Can you look at the name of the plugin folder and tell me if it has `-master` in it?

**Comment by JuanDBB** [comment]
The folder is called m-chart-highcharts-library-master

**Comment by methnen** [comment]
OK, that's the problem. I suspect you downloaded it from the githhub zip download button?

![zip download](https://methnen-dropshare.s3.amazonaws.com/pb-XdIs4H8AVi.png)

That downloads the entire repository and appends the branch name to the directory.

There's a cleaner version of the plugin linked in the Read Me file:

https://github.com/methnen/m-chart-highcharts-library/raw/master/plugin.zip

You can replace the one you have with this one, or you can rename the one you have so that `-master` is no longer at the end of the file name and the message should go away.

**Comment by methnen** [comment]
Wanted to note that going forward this won't be a problem as the WP update stuff should handle everything correctly going forward.

**Comment by JuanDBB** [comment]
Thanks a lot ))
