### ISSUE TITLE
Themes and Oxygen Builder

### ISSUE THREAD

**Issue by imjeffp** [methnen/m-chart#151]
Since my WP site is built with [Oxygen Builder](https://oxygenbuilder.com), I don't have an active theme or even a theme folder to install a Highcharts theme into. Any suggestions? Or a set of step-by-step instructions to set styled mode to true from within the plugin?

**Comment by methnen** [comment]
@imjeffp this is a situation where the filter hooks are probably your solution. 

Take a look at the [m_chart_chart_args](https://github.com/methnen/m-chart/wiki/Action-and-filter-hooks#m_chart_chart_args) hook. The example code even shows exactly how you could use it to change the chart colors in the same ways as a simple theme. 

Usually you would throw this into your functions.php file but since you aren’t using a traditional theme you won’t have one. 

Instead you could create a simple one file plugin and put the code in there. 

Here is a reasonably easy to follow example of how a single file plugin looks:

https://www.dreamhost.com/blog/how-to-create-your-first-wordpress-plugin/
