### ISSUE TITLE
Custom Chart Colors

### ISSUE THREAD

**Issue by buffaloseven** [methnen/m-chart#42]
It would be nice if the UI allowed for custom chart colours; simply entering a HEX code would suffice for each series present on the chart.

**Comment by methnen** [comment]
Hey @buffaloseven if you simply want to change from the default styles for your entire theme vs. doing it per chart, that ability is already there and you could do it by adding a filter method to your theme's functions.php file quite easily.

More details here: https://github.com/methnen/m-chart/wiki/Action-and-filter-hooks#m_chart_chart_args

If you need to do it on a per chart basis, yes, we'd need some UI additions. It's something I have thought of adding a few times, but in most cases a per theme/site color customization has been enough. It remains on my list of items to add.

**Comment by buffaloseven** [comment]
Hmm...looking through the documentation, that could work, however...it gets complicated.

I run a blog that focuses on weather for my region.  I often use different chart colours depending on what sort of weather parameters I want to display to help people intuit what the data is.  Ultimately, I'd like to have cohesion with my colours chosen for various parameters.  You can see my current implementation of highcharts [here](http://aweathermoment.com/metars).

I've been mulling it over in the past few days, and perhaps the best way to implement something like that without getting too complicated could be to allow the user to define colour sets?  So on the WP backend I could define a colour set and add it to the list, then on the front-end I could select which colour set to use?  I'm not sure if that would be more complicated that per-series colouring, but it could have the practical benefits of allowing for a few default templates for people to choose from, even if they don't want to add their own?

I'm not particularly familiar with WordPress PHP (I fumble my way through it), but I'm fairly competent on the HTML/JS side, so if there was a way I could help contribute, I'd gladly give it a shot.

**Comment by methnen** [comment]
Hmm.... I see the problem for your use case.

I added all of the action and filter hooks specifically to allow for non UI based solutions to the sorts of problems like you have. Not that UI based solutions are bad just that they require more time to write on my part and I work on M Chart as I'm able around actual paying work.

I really like your suggestion of having color sets as a drop down since it lends itself to being less work on the part of the person creating the chart then setting colors per series. I'll look into adding that long term.

Basically you want to have a set of styles per chart but based on something like the type of weather being displayed correct?

Short term you could do that through the same filter I mentioned earlier combined with some creative category usage. 

Create a category for each weather type a chart might display. Then on the filter method you'd use the `$post` object to get the category selected for that chart say "Wind & Pressure". Then you'd set the colors and any other style related items in the chart args array you wanted to override for that weather type. It would end up looking something like this:

```php
function m_chart_chart_args( $chart_args, $post, $post_meta, $args ) {
	$category = get_the_category( $post->ID );

	// Makes sure we've got a category to actually work with
	if ( empty( $category ) ) {
		return $chart_args;
	}

	// This code assumes a chart only ever has 1 category selected
	if ( 'wind-pressure' == $category[0]->slug ) {
		$chart_args['colors'] = array(
			'#2f7ed8',
			'#0d233a',
			'#8bbc21',
			'#910000',
			'#1aadce',
			'#492970',
			'#f28f43',
			'#77a1e5',
			'#c42525',
			'#a6c96a',
		);
	} elseif ( 'temprature-dewpoint' == $category[0]->slug ) {
		$chart_args['colors'] = array(
			'#2f7ed8',
			'#0d233a',
			'#8bbc21',
			'#910000',
			'#1aadce',
			'#492970',
			'#f28f43',
			'#77a1e5',
			'#c42525',
			'#a6c96a',
		);
	}

	return $chart_args;
}

add_filter( 'm_chart_chart_args', 'filter_m_chart_chart_args', 10, 4 );
```

Keep in mind I just threw that together and haven't tested it but I think it would work. You'd just drop that into your functions.php file of your theme. 

Note I'm using the category slug instead of the category name to check against just because the slugs are a bit cleaner.

**Comment by buffaloseven** [comment]
I'll give that a try tonight and see how it works.  I'd gladly do the front-end UI stuff once I get a handle on how the front-end and WP backend communicate with each other.  I've done quite a bit of UI development, so I'm often happy to contribute in that way when I can :-)

I agree that a dropdown for "Colour Scheme" would probably work better than individual series colours; you lose a bit of customization, but the benefit would be obvious for a majority of "I just want to make a pretty graph" users.

I assume that the colour array is just passed into highcharts (haven't looked too closely at the source yet), so the colours are applied sequentially to the chart series?

**Comment by methnen** [comment]
Yes, the color array works just like it would as an option in Highcharts. The entire $chart_args array gets converted to a JSON string and then passed to Highcharts. So anything you can do via the Highcharts API: http://api.highcharts.com/highcharts you can add to the $chart_args array.

If you want to contribute to the plugin just fork it and then do a pull request of your changes into this repository.  

That way I can code review and what not before we merge it in.

**Comment by methnen** [comment]
Closing because 1.2 provides a way to handle this now.
