### ISSUE TITLE
How do I donate & some feature suggestions

### ISSUE THREAD

**Issue by OurWeb** [methnen/m-chart#50]
Hey Methnen! 

Thanks so much for making a VERY handy WP charting plugin! Love the spreadsheet integration most. So much that I'd like to donate $15. Do you have a PayPal email address I can shoot the $ over to?

Also, I have some **feature requests**...(praying the first one can come soon!)

1) **Can you make it possible to duplicate a chart???** I need to create hundreds of charts with the same styling, Axis Titles and Data (for the most part). The only thing I need to change is one of the data plots, so it would make my job immensely easier if I didn't have to re-enter all the redundant data and styling options for every single chart. I'm sure this is something _many_ users would appreciate once they've configured a chart they are happy with. Maybe a "Duplicate Chart" button somewhere, either in the editor itself, or added to the "Charts List" hover buttons?  i.e. >  Edit  |  Quick Edit  |  Trash  |  View  |  **Duplicate**

2) **The “Source URL” isn’t working as a live link.**
Is this a compatibly issue with WP 4.4.2? Or is it because I don’t have the HighCharts license for my site? If the license is the issue and I paid for the license, would the problem resolve automatically when I registered my site with HighCharts or is the link in your plugin not set up to recognize whether or not a site is licensed?

3) **I noticed on https://Cloud.HighCharts.com, if a series/data line gets to close to zero, it automatically adds a negative range so the data line doesn’t just look like it's the bottom line of the chart. Can you make that happen on the M-Charts as well? 

4) **Add the “embed this chart” functionality** seen on https://Cloud.HighCharts.com so my website visitors have the option to embed my chart on their site? Might be a good way to get some legitimate backlinks. Of course the "Source URL" would have to be working and be included in the embed code. 

p.s. - also looking VERY forward to the color options for the “Series/Data Colors” functionality you are planing to add!

**Comment by methnen** [comment]
Hey @OurWeb thanks for the ideas.

My thoughts:

1. Duplicating charts probably wouldn't be too difficult to add.  I'll keep that in mind next time I've got some time to spend on the plugin.

2. The source URL thing is a core feature in Highcharts that I'm just piggy backing on top of. Are you saying that when you set a Source value and A source URL value that it's not clickable? I'll have to look into that as it certainly WAS working last time I tried it. Highcharts' licensing is sort of honor based. Basically if you use it commercially you're supposed to buy a license but it's fully featured from the start.

3. This should already be the default behavior. Again it WAS working last time I tried this. But I can investigate if it's not for some reason. The "Force vertical axis to zero" toggle is actually there to work around the feature because sometimes it's annoying to have negative values in the axis like it would normally do.

4. I'm assuming this allows charts to be embedded on other domains? That's a feature I'd love to add and it's been on my list for quite some time I just haven't found the time to do it yet.

The theme stuff should be ready soon I know it's a much wanted/requested feature. It's quite close to finished I just need to finish some of the interface around it and then test it a bit more before pushing the update live.

**Comment by methnen** [comment]
Oh, and if you really want to make a donation send some money to [MercyCorps][https://www.mercycorps.org/].

**Comment by OurWeb** [comment]
Thanks @methnen for the lightning fast response!

All of your assumptions reg. my request are correct. Yes, the "source URL" isn't clickable. In both Safari and Firefox my curser turns into a hand _as though_ it's a link, but the text is grey and I can't click on it. 

I notice the source code on my published page contained this:

> "credits":{"href":null,"text":"source: fbi.gov"}  <

...so the URL doesn't seem to be carrying over for some reason. I'm actually running WP 4.3.3 (w/ Modernizer theme from YIThemes.com). Praying my WP Theme isn't the problem. Can you check if it and the "zero function" works for you on the latest WP 4.4.2? 

I'll send a €15 donation to www.mercycorps.org right now. Very good of you! Good cause! :) Bernie Sanders for president!!! ;)

**Comment by OurWeb** [comment]
One last feature request... can you add the "Chart Subtitle" field found on https://Cloud.HighCharts.com when you get a chance? It's very handy for sub-defining a chart's data.

HOWEVER, if you have to choose any of my suggestions to work on first, my highest priority would still be "Duplicate Chart". I'm confident many users will appreciate having this as an option!

Cheers!

**Comment by methnen** [comment]
Closing since 1.2 solves the issues that haven't been split out of this this request.

**Comment by OurWeb** [comment]
Update: the source links on my charts are now clickable now. Not sure if it was WP update or my theme update that made the difference, but thought you should know it's resolved now.

And thanks for making my other suggestions "enhancement" posts :)
