### ISSUE TITLE
Patch 1.2 and 1.2.1 messed up everything (tldr: PHP >= 5.3.6 is required) 

### ISSUE THREAD

**Issue by AtlasRush** [methnen/m-chart#59]
Hi Methnen! I was really excited to update since the changelog was very tasty, but as soon as I did it, I couldn't modify charts (or at least preview them) anymore. Also, in the settings area, there is no "apply" button...

**Comment by methnen** [comment]
Hey @AtlasRush. Any chance I can see the issue in action somewhere? I'm looking at it right now and not seeing any issues in WP 4.5.1.

I've seen themes causing issues with stuff before though. Is the theme you're using publicly available so I can test with it? Otherwise I'm happy to look into it in whatever way works best for you.

**Comment by methnen** [comment]
Also do you see any errors in your browser's console? Sometimes that can point me to the issue.

**Comment by AtlasRush** [comment]
The theme i'm using is JMagz, a Premium Theme. You want me to send you a link to download it from Themeforest? The previous version didn't give me any problem, while this one instantly bugged itself :\

**Comment by methnen** [comment]
Yes if you can I'd like to try taking a look. The charts are still working from the front end correct?

It might be easiest if you were comfortable passing me a temporary login/pass to a Dev version of your site if you have one.

**Comment by AtlasRush** [comment]
http://www.rehwolution.it/review/reeven-okeanos-1402-cpu-heatsink-recensione/5/
Charts don't load and they actually block the rendering for the rest of the page. How can I give you those credentials privately? Can you write me an e-mail to ciro.sdino@rehwolution.it?

**Comment by methnen** [comment]
Just sent you an email.

**Comment by methnen** [comment]
To keep a public record, the issue was that the new theme code relies on the [DirectoryIterator getExtension](http://php.net/manual/en/directoryiterator.getextension.php) method which was not available in the version of PHP @AtlasRush was running. The extension is in PHP 5.3.6 and later.

I'll be looking at refactoring the code a bit to possibly remove the reliance on the getExtension method.

**Comment by methnen** [comment]
Reopening for a little while in case anyone else comes along with the issue before I can make any updates.
