### ISSUE TITLE
M-Charts is creating empty pages

### ISSUE THREAD

**Issue by OurWeb** [methnen/m-chart#61]
M-Charts is creating pages on my site that are totally empty. I assume the page it creates should at least have the chart on it, right? Seems awfully bad for SEO since Google is penalizing sites that have pages with “thin content”.

In addition, when you create a category for your charts, the category’s page is also empty…showing no posts within the category. 

Does M-Chart really have to create pages and categories? 

Images aren't organized this way in WP and don’t create these problems. 

Hope there's a fix for this.

**Comment by methnen** [comment]
Hey,

It's left open as an option for those who want to have the charts have their own individual pages. HighCharts doesn't create the pages in the sense that Google shouldn't know they are there unless your theme is generating links to them somehow, which would be strange. And actually each individual image can have it's own page as well in WP though again you should create a template meant for displaying them.

In order for the page to have content you'd need to create a template for the custom post type. Since the charts are themselves a custom post type thats pretty normal WP behavior. The same goes for the categories which will always have a page if you know to go specifically to the URL for it but Google isn't going to know about it unless you tell it. 

There's no reason those should be surfaced to Google UNLESS your theme is surfacing them somehow.

It could be I'm misunderstanding your report though.

**Comment by OurWeb** [comment]
Thanks for the quick response! I see your point about Google not finding the pages if there are no links to them. The only problem I have then is that the Category pages are forcing themselves onto my HTML Sitemap page, which WOULD encourage Google to crawl them. 

The only solution I can think of then is to associate the charts to a category that actually has regular posts and delete the categories that I made specifically for the charts.

**Comment by methnen** [comment]
Ah, I see... is there a way to change the sitemap query to check if the category has posts in the normal 'post' post_type before trying to list it in the sitemap? That's the directly I'd immediately look but maybe not straightforward as I don't know how your sitemap is being generated.

**Comment by OurWeb** [comment]
Figured it out! :) I had to edit the individual Category Page itself and use the Yoast SEO's settings found THERE to change the "**Include category in sitemap**" from "**auto**" to "**never include**". That removed the category from my Sitemap Page since my HTML sitemap plugin (WP SEO HTML Sitemap) creates my Sitemap Page automatically from my site's sitemap.

**Comment by methnen** [comment]
Glad to hear you worked it out.
