### ISSUE TITLE
Something broken when making a chart

### ISSUE THREAD

**Issue by petrakid** [methnen/m-chart#76]
After entering the third row of data (pie chart with two columns of data), I am no longer able to save the chart using the Publish/Update button, or save a draft using the Save Draft button.  They're both disabled.  Also, any data that add to the spreadsheet doesn't update the preview of the chart.  The first two rows work fine, but once I add a third row the chart stops updating and disappears.  I think it may switch to a different type of chart but I'm not sure.

<img width="577" alt="2016-08-09" src="https://cloud.githubusercontent.com/assets/9057136/17516374/7eaf5376-5e03-11e6-8418-af6ce49dadc4.png">
<img width="217" alt="2016-08-09 1" src="https://cloud.githubusercontent.com/assets/9057136/17516394/96258854-5e03-11e6-9401-32c2b62f55bc.png">
<img width="663" alt="2016-08-09 2" src="https://cloud.githubusercontent.com/assets/9057136/17516406/b26fc61e-5e03-11e6-9b96-1ffdd8239bda.png">

This is the 4th chart plug in I've tried and my client is getting upset with me.  I may have to resort to just using pictures created in Excel, which is lame.  I don't have any administrative add ons, and I use the Enfold theme (pro version).

**Comment by methnen** [comment]
Hey @petrakid I'm sure we can get things working. The only other time I've see what you are describing it was a server issue. It could also be a JS error of some kind.

By default the plugin makes AJAX requests as settings and data get updated so that the chart preview is always up to date. However, if those requests don't get answered it acts like you've described.

You can try turning off the live preview by going to Charts --> Settings and the selecting the third radio button under Performance. Then save the settings.

This disables the image generation and live previews but it should work around the issue you're describing. You'll have to save to see your changes reflected in the charts but otherwise it works fine.

However, if this is the AJAX requests not being answered you might have deeper problems with your hosting.

The other user I saw run into this issue ended up needing to upgrade his server since it wasn't just failing to respond to the AJAX requests it was also failing to respond to all kinds of stuff and visitors were even getting blank pages periodically.

**Comment by petrakid** [comment]
Thanks I'll do the live preview shut off thing first.  I'm not sure that it's AJAX as I have other addons that use AJAX and they seem to work fine.  Just FYI, I don't remember seeing any console log errors when I check the browser's built-in mechanism.  I'm using Cyberfox, which is a Mozilla-based browser (which runs faster than Firefox).  However I tried it in Edge too and same problem.

**Comment by petrakid** [comment]
Now when I go and add the data, the pie chart continues to update as it should (no reloads, and yes I shut off the live preview), but the Publish/Update button is still remaining disabled.

**Comment by petrakid** [comment]
One more little snippet of information:  I went into the database, to the wp_posts table, found the posts related to my chart and added random data to the post_content field of each post/update/draft.  Then went back to the site to view the chart.  The data I added was displayed but of course no chart.  I then went to edit the chart and there was no data in the spreadsheet.  I imported (again) the data from CSV and BOOM, I was able to update the chart.  I went back into the database and deleted the post_content data from each of the posts, the chart data remained and the chart works.

Could this have something to do with needing something to go into the post_content field??

**Comment by methnen** [comment]
The post_content field is ignored as far as the plugin is concerned. I'm pretty curious at what might have been happening now.

With the live previews turned off there's nothing in the Plugin code that will disable the publish/save button. So it must have been the default WP auto save stuff that was disabling the button.

I'd be happy to take a closer look if this is up on a dev server somewhere that you don't mind me being able to poke at a bit.

**Comment by methnen** [comment]
Closing for the time being as there's been no new information and I'm unable to duplicate this issue.
