### ISSUE TITLE
[Enhancement] Enable Exporting for Graphs

### ISSUE THREAD

**Issue by buffaloseven** [methnen/m-chart#95]
I wanted to enable the exporting module on a per-chart basis to allow people to download an image of the chart on demand directly from the chart interface.

```php
	200    $chart_args = apply_filters( 'm_chart_chart_args', $chart_args, $this->post, $this->post_meta, $this->args );
	201
	202    // Check if Exporting is Enabled
	203    if ($chart_args['exporting']['enabled'] == true) {
	204    	wp_enqueue_script('highcharts-exporting');
	205    }
	206
	207    // Set the cache, we'll regenerate this when someone updates the post
	208    if ( $cache ) {
	209    	wp_cache_set( $cache_key, $chart_args, m_chart()->slug );
	210    }
```

I defined `highcharts-exporting` in `class-m-chart.php` alongside `highcharts` and `highcharts-more`, and then added lines 202-205 above in `class-m-chart-highcharts.php`. Works like a charm. If the chart theme defines exporting as enabled, the button shows up correctly.

Perhaps this could be implemented as a checkbox in the admin panel so it's part of the post_meta? Or I'll just keep it for myself. I wish I could add a button directly in the chart interface to link to the image m-chart creates already, but I don't think that's possible via the Highcharts API.

**Comment by methnen** [comment]
Hey @buffaloseven yeah, Highcharts own image generation stuff is a bit limited and doesn't have a built in way to send the user to a pre generated image. I built my own image generation because I was unhappy with the Highcharts stuff myself which generates a low res image that looks terrible on a high dpi screen.

Thinking about this I'm wondering if a simple solution would be to add some action hooks to the function that generates the charts (this would be possibly helpful for other things anyway). You could then hook into that and append a link to the charts thumbnail (where the pre generated images are stored) when appropriate. It wouldn't show up as part of the Highcharts interface but it would let you optionally serve up the higher quality image on a per chart basis. 

In terms of interface on the admin end if you wanted you can do that by adding a meta box and attaching it to the `m-chart` post type. Then you could add a toggle quite easily and store it on save_post or however you wanted. You could name it something like "Additional Chart Settings" or whatever.

Happy to help guide you in that however you want and you're welcome to borrow any code you need from the plugin of course.

But this is potentially a useful feature for others so I might just add it for everyone.

I'll need to think through it a bit more.

If you want to get the

**Comment by buffaloseven** [comment]
My initial thought was just to enable the Highcharts-native image generation. My plan is to have a long data set (daily data, going back years), and then allow the user to easily zoom to to the last 30, 90, or 365 days. The hope would be that they could then just use the native image exporting to save it as an image.

**Comment by methnen** [comment]
Hey @buffaloseven I believe an easy solution for this would be the action hooks added to get_chart.

You could call either one and then enqueue the export script which is already registered with Wordpress at that point.

This is all you'd need:

`wp_enqueue_script( 'highcharts-exporting' ); `
