### ISSUE TITLE
[Request] Toggle Data Points Option

### ISSUE THREAD

**Issue by jwbriney** [methnen/m-chart#96]
I noticed when I create line and spline graphs with a lot of data, the points get close enough that the individual markers disappear and you get just the line. But when I make one with fewer points the individual markers show up. Is there a way to turn the data markers on and off for each graph?

**Comment by buffaloseven** [comment]
Create a custom theme and enable markers for the series in the `plotOptions` settings:

'''json 
plotOptions: {
    series: {
        marker: {
            enabled: true
        }
    }
}'''

You can see theAPI reference here: http://api.highcharts.com/highcharts/plotOptions.series.marker.enabled

But note that force-enabling markers may introduce performance problems if you have a large data set.

**Comment by methnen** [comment]
Hey @jwbriney as @buffaloseven mentioned this is potential performance issue for extremely large data sets which is why Highcharts automatically disables them when you go over a certain size data set.

His suggestion is your best bet short term especially since it will give you a working solution now without waiting for me to possibly implement this in a future version.

I threw together an **untested** theme for you and attached it to this reply.

[force-markers.zip](https://github.com/methnen/m-chart/files/973959/force-markers.zip)

**Comment by jwbriney** [comment]
Thanks guys, that worked perfectly. Appreciate it.
